### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by MicaelCarvalho** [torralba-lab/im2recipe#1]
Hello,

First of all, thank you very much for releasing the source code and the data used for your experiments. :-)

The file `det_ingrs.json` seems to be missing. We were able to run `bigrams.py` by removing `utils.Layer.INGRS` from the dataset list, but this file seems to be fundamental for `tokenize_instructions.py`.

Inside `recipe1M_layers.tar.gz` there are only two files : `layer1.json` (1.4GB) and `layer2.json` (132GB). We found traces in the code indicating the existence of a `layer3.json`; should it be there or is this file deprecated ?

We could not find the file `food101_classes_renamed.txt` neither.

Thanks in advance for your help !

**Comment by nhynes** [comment]
Thanks for the bug report! 76193b0a0c2d278edadf6a18eac466f609858485 adds `food101_classes_renamed.txt` and `det_ingrs.json` is now available for [download](http://im2recipe.csail.mit.edu/dataset/download/).
