### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by Hossambeso** [torralba-lab/im2recipe#13]
I need python code for the following problem

Kayla has completed her analysis of the system. She has decided to start the design of the new system with the design of the software. From her analysis she knows that one thing the system has to do is to calculate the required amount of each ingredient.
She designs an algorithm that
•	reads a file to get the total number of different ingredients Sebastian keeps in stock (Num_Ingredients)
•	for each bread item (Product_ID) ordered, uses recipe data and the number of items ordered (Num _ Ord) to
•	calculate the amount of each ingredient required for that item (Amount_ Req)
•	adds the ingredient amounts required for each item to get the total quantity needed for each ingredient Qty ()

The procedure will have passed to it data that lists the amount of each ingredient required for every bread item made by the bakery (Product_Recipes)

**Comment by Hossambeso** [comment]
any help

**Comment by nhynes** [comment]
Hi @Hossambeso, it sounds like your problem is generic enough that you can try posting it on StackOverflow (although they might suspect that it's a homework problem and not answer it ;).
