### ISSUE TITLE
HOW CAN I GET YOUR DATASET?

### ISSUE THREAD

**Issue by li10141110** [torralba-lab/im2recipe#14]
I'm from China and I have sighed up your DATASET, but I can't get a link.My count 364975573@qq.com. Thank you in advance!

**Comment by nhynes** [comment]
Hi Jason, you'll have to sign up with an academic email. Sorry for any inconvenience!

**Comment by li10141110** [comment]
@nhynes Thank you! Is htliu@tju.edu.cn a right academic email?I'm from TianJin University, which is a famous school in China. Thank for your time!

**Comment by nhynes** [comment]
@li10141110 you might want to check your email spam/junk folder, but just in case it's not there, I went ahead and manually approved your registration. I hope that you find the dataset useful in your research!

**Comment by li10141110** [comment]
Thank you very much!
