### ISSUE TITLE
High level classes (course categories: "main course", "dessert", etc.)

### ISSUE THREAD

**Issue by Cadene** [torralba-lab/im2recipe#15]
Hello,

Thanks a lot for your work. Where could I find in your dataset the information related to the course categories (Figure2 in your article: http://im2recipe.csail.mit.edu/im2recipe.pdf)?

Thanks for your help :)

**Comment by nhynes** [comment]
These data weren't released with the dataset as they weren't consistent[ly available]. If you send me an email detailing why you need them, I can see if I can dredge something up :)

**Comment by Cadene** [comment]
@nhynes Thanks :)
