### ISSUE TITLE
How much iterate did you the learning in your paper?

### ISSUE THREAD

**Issue by tom-ock** [torralba-lab/im2recipe#19]
Hello.
I'm going to replicate your experiment in your paper for confirm whether it works or not.
For replication, I want to know a same iteration number as one used in your experiment.
But I couldn't find this number in your paper.
How much iterate did you the learning in your paper?

**Comment by nhynes** [comment]
A good strategy would be to [run until the validation error stops decreasing](https://github.com/torralba-lab/im2recipe/blob/master/args.lua#L65).
