### ISSUE TITLE
File data/remove1M.txt not found

### ISSUE THREAD

**Issue by Cadene** [torralba-lab/im2recipe#2]
Hi,

First of all, thanks for your release :)

I encountered some issue with the file `mk_dataset.py` at [line 69](https://github.com/Cadene/im2recipe/blob/master/pyscripts/mk_dataset.py#L69).

I suppose that the file `remove1M.txt` was needed before your current release. I managed to run the code by commenting/modifying all the lines involving the variable `remove_ids` as told in the comments:

- [line 25](https://github.com/Cadene/im2recipe/blob/master/pyscripts/mk_dataset.py#L25)
- [line 38](https://github.com/Cadene/im2recipe/blob/master/pyscripts/mk_dataset.py#L38)
- [line 69](https://github.com/Cadene/im2recipe/blob/master/pyscripts/mk_dataset.py#L69)
- [line 108](https://github.com/Cadene/im2recipe/blob/master/pyscripts/mk_dataset.py#L108)
- [line 142](https://github.com/Cadene/im2recipe/blob/master/pyscripts/mk_dataset.py#L142)

Could you please confirm that it should be done that way and that I am not missing something?

Thanks for your help ;D

**Comment by amaiasalvador** [comment]
Hi,

we have added the ```remove1M.txt``` file, which is required to ensure there are no duplicates between samples in different partitions.
