### ISSUE TITLE
Download dataset

### ISSUE THREAD

**Issue by NerdPraise** [torralba-lab/im2recipe#29]
Hello, I am a  postgraduate student from covenant university trying to get the recipe1m+ dataset. I have tried registering on the platform http://im2recipe.csail.mit.edu/ but it keeps returning 500 internal error. 
Can I have it sent to praise.ajayi@stu.cu.edu.ng?
Thank you.

**Comment by NerdPraise** [comment]
@nhynes @Cadene @amaiasalvador @jmarintur

**Comment by frankamania** [comment]
i need it too anusdas9@gmail.com email me

**Comment by gu18168** [comment]
gu18168@hust.edu.cn
I need it too

**Comment by ntuyt** [comment]
tyu008@ntu.edu.sg
I need it too

**Comment by BotYue** [comment]
yuecao@purdue.edu 
I need it too. Thank you.

**Comment by frankamania** [comment]
https://data.lip6.fr/cadene/im2recipe/

this is something I found on the internet

**Comment by jks17** [comment]
I have the same issue
jks17@ic.ac.uk 

Thanks

**Comment by TengfeiLiu966** [comment]
I have the same issue
tfliu@emails.bjut.edu.cn

Thanks

**Comment by n1tr0maverick** [comment]
I have the same issue :/
aravind.ashok@student.uva.nl

Kind Regards

**Comment by jmarintur** [comment]
Hi everyone, please send an email to jmarin@csail.mit.edu using your university / public institution email, and I'll send you the links.
