### ISSUE TITLE
No corresponding file for logfile.txt ?

### ISSUE THREAD

**Issue by MicaelCarvalho** [torralba-lab/im2recipe#4]
Hello,

On the README, there is a paragraph stating that one can plot loss curves using `logfile.txt` as input, as follows: `plotcurve.py -logfile /path/to/logfile.txt`.

I could not, however, find any file, parameter or output of the training step that corresponds to this file. Could you please inform me where it comes from? Or is it some old code that is no longer used? Looking at the structure of `plotcurve.py` it seems this file should be in the CSV format.

Thank you in advance :-)

**Comment by amaiasalvador** [comment]
Hi,

```logifle.txt``` should contain the stdout of ```main.lua```. Redirect it when you launch training with ```th main.lua > /path/to/logfile.txt ```. I have included this in the README now to avoid future confusion. Many thanks !
