### ISSUE TITLE
Request for Access to Dataset

### ISSUE THREAD

**Issue by Yuran-7** [torralba-lab/im2recipe#45]
Hello,

I hope this message finds you well. I am a student at Huazhong University of Science and Technology, currently conducting research that aligns closely with your work. I am very interested in accessing the dataset used in your paper, as it would be highly beneficial for my studies.

Would it be possible for you to grant me access to this dataset?If possible, please send the access information to either of the following email addresses: [1724277428@qq.com](mailto:1724277428@qq.com) or [m202477005@hust.edu.cn](mailto:m202477005@hust.edu.cn).

Thank you very much for your time and consideration.

Best regards,
Shihuan Yu
Huazhong University of Science and Technology

**Comment by jmarintur** [comment]
Hi @Yuran-7, I've just updated the downloading section. You should be able now to fill the Google form.
