### ISSUE TITLE
Request for Access to the Recipes1M Dataaset

### ISSUE THREAD

**Issue by dmgcsilva** [torralba-lab/im2recipe#46]
Hi,

My name is Diogo Silva. I am a PhD student at NOVA School of Science and Technology and I am currently a research scholar at CMU. My work focuses on recipe-related tasks, making this dataset extremely useful for my research.

Could please share the dataset or any URLs that I can use to access it? My email is dgloriac@andrew.cmu.edu

The dataset would be used solely for research purposes.

Many thanks,
Diogo Silva

**Comment by jmarintur** [comment]
Hi @dmgcsilva, I've just updated the Dataset section where we provide the Google form.
