### ISSUE TITLE
Can't download the dataset

### ISSUE THREAD

**Issue by piffarettig** [torralba-lab/im2recipe#8]
When I want to download the dataset it asks me to register and then login (a couple of months ago it was available for everyone). When I register and verify my email it says:

```
Thank you for verifying your email address. Your request for access to the dataset is now being reviewed. You will be notified when it is approved.
In the meantime, if you wish to inquire about the status of your request, please email im2recipe@csail.mit.edu.
```

However I haven't received any approval, and when I email that address, it says the mailbox is unavailable. So I'm stuck with no dataset. Could you please pass a link to download the dataset? I'd appreciate it very much

Thanks

**Comment by nhynes** [comment]
> a couple of months ago it was available for everyone

Nope, it's always been behind a login page :)

> Could you please pass a link to download the dataset?

I'd love to but you didn't include an organization and there's no telling from your website that you don't represent a commercial entity. Sorry!
